# Generated by Django 4.2.4 on 2023-08-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('types', models.CharField(choices=[('department', 'Department'), ('team', 'Team'), ('position', 'Position')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_node', to='base.node')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_node', to='base.node')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_node', to='base.node')),
            ],
        ),
    ]
